In [ ]:
#Practice Questions for numpy
#Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.
#Find common elements between A and B. [Hint : Intersection of two sets]
#Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]
#Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [63]:
import numpy as np
A = np.array(range(4))
B = np.array([4,5,6,7])
C = np.hstack((A,B))
D = np.vstack((A,B))
print(C)
print(D)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


In [40]:
A = np.array([1,2,3,4,5,6])
B = np.array([4,5,6,7,8,9])
incommon = np.intersect1d(A, B)
print(incommon)


[4 5 6]


In [46]:
A = np.random.randint(-10, 21, size = 20)
specificrange = A[np.where((A >= 5) & (A <= 10))]
print(specificrange)




[ 8 10  6 10  7]


In [48]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
filtered = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print(filtered)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [16]:
#Practice Questions for Pandas
#From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
#df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
#Replace missing values in Min.Price and Max.Price columns with their respective mean.
#df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
#How to get the rows of a dataframe with row sum > 100?
#df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [33]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
for i in range(94):
    if i % 20 == 0:
        print(df.loc[i, ['Manufacturer', 'Model','Type']])

Manufacturer      Acura
Model           Integra
Type              Small
Name: 0, dtype: object
Manufacturer    Chrysler
Model            LeBaron
Type             Compact
Name: 20, dtype: object
Manufacturer      Honda
Model           Prelude
Type             Sporty
Name: 40, dtype: object
Manufacturer    Mercury
Model            Cougar
Type            Midsize
Name: 60, dtype: object
Manufacturer    Subaru
Model           Loyale
Type             Small
Name: 80, dtype: object


In [52]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
minpricemean = df['Min.Price'].mean()
maxpricemean = df['Max.Price'].mean()
df['Min.Price'] = df['Min.Price'].fillna(minpricemean)
df['Max.Price'] = df['Max.Price'].fillna(maxpricemean)
print(df)

   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0   
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0   
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31

In [56]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
result = df[df.sum(axis=1) > 100]
print(result)

     0   1   2   3
2   18  37  39  29
4   22  26  36  29
7   30  15  37  29
10  38  17  30  16
11  36  38  18  12
12  15  34  16  36
13  37  13  33  22
